version: '3.1'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  myadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
    ports:
      - 8003:80
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
volumes:
  db_data: {}
  wordpress_data: {}